name: "Terraform CLI"

on:
  push:
    branches:
      - main
      - feat/cicd
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
            credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -lock=false
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: vjoksimovic
          exclude-workflow-initiator-as-approver: false
          issue-title: Approve Infrastructure Deployment

      - name: Terraform Apply
        if: github.ref == 'refs/heads/feat/cicd' && github.event_name == 'push'
        run: terraform apply -auto-approve -lock=false
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}